### ISSUE TITLE
custom_from installed via composer 

### ISSUE THREAD

**Issue by paulkoan** [r3c/CustomFrom#14]
This may be a roundcube issue, but other plugins seem to work without issue.

If I add 

     "roundcube/custom-from": "dev-master"

to the roundcube main composor.json `require` entry, and run the phar, it successfully clones custom_from, however it puts the custom_from.php at `plugins/custom_from/custom_from/custom_from.php` 

Roundcube plugin installer looks for the php in the root:

    [09-Jun-2015 09:10:49 +1000]: <dsafkq0m> PHP Error: Failed to load plugin file /var/lib/roundcube/plugins/custom_from/custom_from.php in /usr/share/roundcube/program/lib/Roundcube/rcube_plugin_api.php on line 198 

I have to move everything up a level to get it into the right place.

**Comment by r3c** [comment]
Seems Composer doesn't allow installing from anywhere else than repository root. I would have prefered to avoid that since it means mixing plugin code files with README & other repo-level files. Should be better now, but that's an unfortunate limitation from Composer in my opinion.
